version: "3.9"

services:
  user_service:
    build:
      context: ./user_service
    container_name: user_service
    ports:
      - "8000:8000"

  post_service:
    build:
      context: ./post_service
    container_name: post_service
    ports:
      - "8001:8001"
    depends_on:
      - user_service
  
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  pgdata:

